# Use vscode-restclient to run, auto saves cookies

POST http://localhost:3035/login HTTP/1.1
Content-type: application/json

{
    "company_recid": 1000
}

###
GET http://localhost:3035/ajax/monitoring_api.php?type=devices

###
GET http://localhost:3035/ajax/monitoring_api.php?type=device&device=1006

###
GET http://localhost:3035/ajax/monitoring_api.php?type=devicehistory&device=1006

###
GET http://localhost:3035/ajax/monitoring_api.php?type=device&device=1006&startdate={{$timestamp -2 m}}&enddate={{$timestamp}}
